<a href="https://colab.research.google.com/github/Richa30407/Phishing-URL-Detection-ML/blob/main/phishing_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

data = pd.read_csv("malicious_phish.csv")

data.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [3]:

print("Total Links Count:")
print(data['type'].value_counts())
print("-" * 30)
data['url_length'] = data['url'].apply(len)

data.head()

Total Links Count:
type
benign        428103
defacement     96457
phishing       94111
malware        32520
Name: count, dtype: int64
------------------------------

                                                 url        type  url_length
0                                   br-icloud.com.br    phishing          16
1                mp3raid.com/music/krizz_kaliko.html      benign          35
2                    bopsecrets.org/rexroth/cr/1.htm      benign          31
3  http://www.garage-pirenne.be/index.php?option=...  defacement          88
4  http://adventure-nicaragua.net/index.php?optio...  defacement         235